name: SSH to Remote Host

on:
  push:
    branches:
      - master  # or your branch

jobs:
  ssh-remote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH key and known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 4422 ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: SSH and run remote command
        run: |
          ssh -i ~/.ssh/id_rsa -p 4422 ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "echo '✅ SSH connection successful!'"

      - name: SSH and run remote command
        run: |
          ssh -i ~/.ssh/id_rsa -p 4422 ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "echo '✅ SSH connection successful!'"
